---
## Define the token in yaml or environment variable "GITHUB_TOKEN"
#token: "XxxXXXXxxxx"
actions:
  - day: 14
    last: true
    action: close
    message: |
              Hi _USER_ this PR exceeded _SINCE_ days in open state.
              We are trying to encourage developers to integrate with master quicker ideally daily.
              I will **close** this PR now.
              Please open a new PR if this branch is still needed.

  - day: 12
    action: warn
    message: |
              Hi _USER_ this PR exceeded _SINCE_ days in open state.
              We are trying to encourage developers to integrate with master quicker ideally daily.
              This is the last warning I will close this PR in _TILL_ days.
  - day: 7
    action: warn
    message: |
              Hi _USER_ this PR exceeded _SINCE_ days in open state.
              We are trying to encourage developers to integrate with master quicker ideally daily.
              I will close this PR in _TILL_ days.

  - day: 1
    action: warn
    message: |
              Hi _USER_ we are trying to encourage developers to integrate with master quicker ideally daily.

repos:
 - "ahelal/avm"
 - "ahelal/t-template"
 - "ahelal/ansible-concourse"
